version: '2'

services:
  next_db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXT_DB_PASS}
      - MYSQL_PASSWORD=${NEXT_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=2048M

  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 9090:80
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXT_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=next_db
      - VIRTUAL_HOST=nextcloud.${HOST_DOMAIN}
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=nextcloud.${HOST_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL_DOMAIN}
    depends_on:
      - next_db

networks:
  default:
    external:
      name: nginx-proxy
