version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASS}
      - WORDPRESS_DB_NAME=wordpress
      - VIRTUAL_HOST=${HOST_DOMAIN}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${HOST_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL_DOMAIN}
    volumes:
      - ./data/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${WP_DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
    volumes:
      - ./data/db:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
